version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: dev
    rebase-strategy: auto
    groups:
      patch-updates:
        update-types:
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: dev
    rebase-strategy: auto
