server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # SPA: redirect all routes to index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # task-service
    location /items {
        proxy_pass http://task-service:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /auth {
        proxy_pass http://task-service:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # project-service
    location /projects {
        proxy_pass http://project-service:3002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # notification-service
    location /notifications {
        proxy_pass http://notification-service:3003;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
