sonar.projectKey=archi-logicielle
sonar.projectName=Archi Logicielle — Microservices
sonar.projectVersion=1.0.0

sonar.sources=services/task-service/src,services/project-service/src,services/notification-service/src,frontend/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.test.ts,**/e2e/**

sonar.javascript.lcov.reportPaths=services/task-service/coverage/lcov.info,services/project-service/coverage/lcov.info

sonar.typescript.tsconfigPaths=services/task-service/tsconfig.json,services/project-service/tsconfig.json,services/notification-service/tsconfig.json,frontend/tsconfig.json

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000